# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Running tests on push to main

on:
  push:
    branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.11.14

            - name: Install Dependencies
              run:
                pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Run test cases
              run:
                pytest test_loan_app_cicd.py
        